name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: hirocapital
  REGION: europe-west1
  REPO_NAME: integrated-resource-optimizer
  SERVICE_NAME: integrated-resource-optimizer-staging

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get-sha.outputs.SHORT_SHA }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Short SHA
        id: get-sha
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/hiro:${{ steps.get-sha.outputs.SHORT_SHA }} \
            --build-arg HUBSPOT_TOKEN=${{ secrets.HUBSPOT_TOKEN_DEV }} .

      - name: Push Docker image
        run: docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/hiro:${{ steps.get-sha.outputs.SHORT_SHA }}

  deploy:
    name: Deploy to Cloud Run
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/hiro:${{ needs.build.outputs.image_tag }}
          flags: '--no-allow-unauthenticated'

      - name: Set IAP Policy
        run: |
          gcloud run services add-iam-policy-binding ${{ env.SERVICE_NAME }} \
            --region=${{ env.REGION }} \
            --member='domain:hiro.capital' \
            --role='roles/iap.httpsResourceAccessor'
